version: '3'

services:
  # DJANGO
  django:
    extends:
      file: docker-compose-base.yml
      service: django
    command: /compose/start
    depends_on:
      - postgres
  # POSTGRES
  postgres:
    extends:
      file: docker-compose-base.yml
      service: postgres
  # ANGULAR
  angular:
    command: /compose/start
    extends:
      file: docker-compose-base.yml
      service: angular
  # NGINX
  nginx:
    command: /compose/start
    extends:
      file: docker-compose-base.yml
      service: nginx
    depends_on:
      django:
        condition: service_started
      angular:
        condition: service_completed_successfully
    volumes:
      - ./nginx:/src



networks:
  localhost:

volumes:
  postgres_db: