version: '3'

services:
  # DJANGO
  django:
    build:
      context: .
      dockerfile: ./compose/backend/Dockerfile
    env_file:
      - ./env/host_env
      - ./env/django_env
      - ./env/post_env
    volumes:
      - ./nginx/static:/src/static
    expose:
      - 5000
    networks:
      - localhost
  # POSTGRES
  postgres:
    image: "postgres:14.4"
    env_file:
      - ./env/post_env
    expose:
      - 5432
    networks:
      - localhost
    volumes:
      - postgres_db:/var/lib/postgresql/data
  # ANGULAR
  angular:
    build:
      context: .
      dockerfile: ./compose/frontend/Dockerfile
    env_file:
      - ./env/host_env
    volumes:
      - ./nginx/:/src/frontend_output
  # NGINX
  nginx:
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    ports:
      - "80:80"
    networks:
      - localhost

networks:
  localhost:

volumes:
  postgres_db: