version: '3'

services:
  # DJANGO
  django:
    extends:
      file: docker-compose-base.yml
      service: django
    depends_on:
      - postgres
    # command: sleep 1d # Used for makemigration | migrate
    command: /compose/start
    volumes:
      - ./backend:/src
      - ./nginx/static:/src/static

  # POSTGRES
  postgres:
    extends:
      file: docker-compose-base.yml
      service: postgres
  # ANGULAR
  angular:
    volumes:
      - ./frontend:/src
    extends:
      file: docker-compose-base.yml
      service: angular
    # Angular ng server
    command: /compose/local-start
    networks:
      - localhost
    expose:
      - 4200
  # NGINX
  nginx:
    command: /compose/local-start
    extends:
      file: docker-compose-base.yml
      service: nginx
    depends_on:
      - angular
      - django

networks:
  localhost:

volumes:
  postgres_db: