version: '3'

services:
  # DJANGO
  django:
    entrypoint: bash ./start
    extends:
      file: docker-compose-base.yml
      service: django
    depends_on:
      - postgres
    # command: sleep 1d # Used for makemigration | migrate
    volumes:
      - ./backend:/src
      - type: bind
        source: ./nginx/static
        target: /src/static

  # POSTGRES
  postgres:
    extends:
      file: docker-compose-base.yml
      service: postgres
  # ANGULAR
  angular:
    entrypoint: ng s
    volumes:
      - ./frontend:/src
    extends:
      file: docker-compose-base.yml
      service: angular
  # NGINX
  nginx:
    extends:
      file: docker-compose-base.yml
      service: nginx
    networks:
      - localhost
    depends_on:
      - django

networks:
  localhost:

volumes:
  postgres_db: