# Generated by Django 3.2.9 on 2022-01-15 11:23

import apps.users.models
import apps.utils.tools
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, error_messages={'unique': 'This email is already registed'}, max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, db_index=True, error_messages={'unique': 'This phone is already registed'}, max_length=12, unique=True, validators=[apps.utils.tools.validate_phonenumber])),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', apps.users.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, choices=[('', ''), ('CA', 'CITY A'), ('CB', 'CITY B'), ('CC', 'CITY C')], max_length=100)),
                ('province', models.CharField(blank=True, choices=[('', ''), ('PA', 'PROVINCE A'), ('PB', 'PROVINCE B'), ('PC', 'PROVINCE C')], max_length=100)),
                ('default_address', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
